### ISSUE TITLE
hover_doc, signature_help commands are not working

### ISSUE THREAD

**Issue by IgnFed** [glepnir/lspsaga.nvim#261]
### Description
Following the documentation of this plugins, i did this :

![image](https://user-images.githubusercontent.com/70576040/139535966-73f23eda-6711-4c7f-ae82-01b77787c4d3.png)

**Expected Behavior**
Like the documentation, this command should display a pop-up window with the description of the element (functions, object, etc.)

**Actual Behavior**
theyThey do nothing. Just are not working 
**(obviously, i've tried to change the commands key and using the render_doc and the signature_help function)**

in the image

## I'm trying to use the Typescript language
- nvim --version output:  0.5.0 
- Operating system: Windows 10

</details>

**Comment by IgnFed** [comment]
Also, the preview_definition command causes my termial to freeze.

**Comment by felixr** [comment]
I am having the same issue and I tracked down the issue to a change in the lsp-handler signature in https://github.com/neovim/neovim/commit/23fe6dba138859c1c22850b9ce76219141f546a0

In https://github.com/glepnir/lspsaga.nvim/blob/cb0e35d2e594ff7a9c408d2e382945d56336c040/lua/lspsaga/hover.lua#L19
the code assumes `(err, method, result)` but it gets `(err, result, ctx)`. `method` needs to be `ctx.method` and the arguments need to be reordered.

**Comment by felixr** [comment]
The handler signature change was reported in  #241 and there are potentially more handlers that need to be updated.

**Comment by IgnFed** [comment]
I've updated the plugin, but still is not working.
Even i've tried to execute the action directly from the cmd, but the result id the same...

**Comment by rkshthrmsh** [comment]
Has this been fixed? Still facing the issue. Is there a particular version in which it was fixed?
```
Error executing Lua callback: .../share/nvim/plugged/lspsaga.nvim/lua/lspsaga/command.lua:47: attempt to call a nil value
stack traceback:
        .../share/nvim/plugged/lspsaga.nvim/lua/lspsaga/command.lua:47: in function 'load_command'
        ...local/share/nvim/plugged/lspsaga.nvim/plugin/lspsaga.lua:83: in function <...local/share/nvim/plugged/lspsaga.nvim/plugin/lspsaga.lua:82>
```

**Comment by glepnir** [comment]
please check readme usage.

**Comment by cruzluna** [comment]
@rkshthrmsh Was your problem resolved?  I am having similar issue. 
`Error executing Lua callback: ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:60: attempt to c
all a nil value
stack traceback:
        ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:60: in function 'load_command'
        ...m/site/pack/packer/start/lspsaga.nvim/plugin/lspsaga.lua:8: in function <...m/site/pack/packer/
start/lspsaga.nvim/plugin/lspsaga.lua:7>`

**Comment by cruzluna** [comment]
The warning is actually clear. To use hover you need to add markdown as a parser 
![image](https://user-images.githubusercontent.com/73450306/215356989-788f4349-30ef-4397-a989-540e59d9d912.png)
