### ISSUE TITLE
Incorrect syntax highlighting in the preview window

### ISSUE THREAD

**Issue by zhyu** [glepnir/lspsaga.nvim#424]
### Description
When using the definition preview feature, the syntax highlighting could be incorrect in the preview window.

**Expected Behavior**
The syntax highlighting is correct.

**Actual Behavior**
Incorrect syntax highlighting due to partial codes being displayed?
![image](https://user-images.githubusercontent.com/1728523/184315606-fa849cf9-f70e-4f9f-811e-a29d139f97b1.png)

**Neovim Built in Behavior**
I'm not aware of an equivalent built-in handler in neovim to preview definition directly.
 
### Details

<details><summary>Reproduce</summary>

1. preview the definition of `test_method` with the following snippet
```py
class TestClass:
    def __init__(self):
        """
        This
        is
        a
        class
        """
        pass

    def test_method(self):
        """
        This
        is
        a
        method
        """
        pass



c = TestClass()
c.test_method()
```
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Operating system: ArchLinux
- lspsaga commit: `86512e7`

</details>

**Comment by glepnir** [comment]
does the definition preview in finder is correct?

**Comment by glepnir** [comment]
It works fine in finder. I plan to remove definition preview . because it's duplicate . finder also do it.

**Comment by glepnir** [comment]
fixed in version2 .it works like this

![image](https://user-images.githubusercontent.com/41671631/184477457-f4ca99d7-1b5e-4e6f-9390-98659b8610c6.png)

**Comment by zhyu** [comment]
I just tried version 2, the issue persists. 
@glepnir Please note, the highlighting issue happens when previewing the definition of `test_method` in the code snippet I shared. The screenshot you shared above is previewing the definition of `TestClass`.

I confirm the preview works fine in finder.
