### ISSUE TITLE
Outline error

### ISSUE THREAD

**Issue by Jezda1337** [glepnir/lspsaga.nvim#792]
### Describe the bug

Open the outline buffer press "o" to go on selected fun, return back to buffer go up and down and get error when trying to go to fun again. here is the video:

https://user-images.githubusercontent.com/42359294/215364964-de9632e7-d8fa-45fd-8034-0ade162b46b6.mov

### Steps to reproduce

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--single-branch",
		"git@github.com:folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

require("lazy").setup({
	"neovim/nvim-lspconfig",
	{
		"glepnir/lspsaga.nvim",
		event = "BufRead",
		config = function()
			require("lspsaga").setup({})
		end,
		dependencies = { { "nvim-tree/nvim-web-devicons" } },
	},
	{
		"nvim-treesitter/nvim-treesitter",
		run = function()
			local ts_update = require("nvim-treesitter.install").update({ with_sync = true })
			ts_update()
		end,
	},
})

local keymap = vim.keymap.set

keymap("n", "K", "<cmd>Lspsaga hover_doc<CR>")
keymap("n", "<space>o", "<cmd>Lspsaga outline<CR>")

require'lspconfig'.tsserver.setup({})

### Expected behavior

Should give me a pop up win of current fun or anything else that I'm on, and after pressing 'o' should go to func or anything else.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-834+g4c90a84c6

### lspsaga commit

last I guess.

### Terminal name/version

kitty Version 0.26.5 (0.26.5)

**Comment by glepnir** [comment]
which commit ? i just pushed a commit for outline

**Comment by Jezda1337** [comment]
I tested again on last commit and the problem is still there. #[4fd71bc](https://github.com/glepnir/lspsaga.nvim/commit/4fd71bc358efe82a879e27e0e872c09c801993df)

**Comment by glepnir** [comment]
I will test it later.
